// Generated by OpenAI GPT-5.5 for DataForge cached Fal AI preview assets.
import Image, { type StaticImageData } from "next/image";
import cavalloPreview from "../../data/animals/fal-ai-generated/cavallo/OIP---MGqQIhmz3OEPYP-46_xwHaFj.jpeg";
import elefantePreview from "../../data/animals/fal-ai-generated/elefante/OIP--3aF2OpzGKcdI6FHil50qQHaFj.jpeg";
import farfallaPreview from "../../data/animals/fal-ai-generated/farfalla/OIP--3xxJkezSkNzxrQaxlhv-QHaHa.jpeg";
import gallinaPreview from "../../data/animals/fal-ai-generated/gallina/10.jpeg";
import gattoPreview from "../../data/animals/fal-ai-generated/gatto/1.jpeg";
import muccaPreview from "../../data/animals/fal-ai-generated/mucca/OIP---lAIbDlHKmejDpqrXq6vAAAAA.jpeg";
import pecoraPreview from "../../data/animals/fal-ai-generated/pecora/OIP--5EOVD9HIiHEqNd8PZjFogHaII.jpeg";
import ragnoPreview from "../../data/animals/fal-ai-generated/ragno/OIP--1GKxNzkhVbR_eyVRCdp9QHaE6.jpeg";
import scoiattoloPreview from "../../data/animals/fal-ai-generated/scoiattolo/OIP--0Yr2a_yg2hs5QgCoHAOnAHaLJ.jpeg";
import styles from "./fal-preview-gallery.module.css";

type FalPreviewAsset = {
  id: string;
  className: string;
  provider: "fal.ai";
  source: "synthetic";
  badge: "✨ Fal AI" | "At Cap";
  image?: StaticImageData;
  sourcePath?: string;
  prompt: string;
  rawCount: number;
  generatedCount: number;
  majorityClassCap: number;
};

const majorityClassCap = 100;

const previewInputs: Array<{
  className: string;
  rawCount: number;
  image?: StaticImageData;
  fileName?: string;
}> = [
  { className: "cane", rawCount: 100 },
  {
    className: "cavallo",
    rawCount: 90,
    image: cavalloPreview,
    fileName: "OIP---MGqQIhmz3OEPYP-46_xwHaFj.jpeg",
  },
  {
    className: "elefante",
    rawCount: 80,
    image: elefantePreview,
    fileName: "OIP--3aF2OpzGKcdI6FHil50qQHaFj.jpeg",
  },
  {
    className: "farfalla",
    rawCount: 70,
    image: farfallaPreview,
    fileName: "OIP--3xxJkezSkNzxrQaxlhv-QHaHa.jpeg",
  },
  {
    className: "gallina",
    rawCount: 60,
    image: gallinaPreview,
    fileName: "10.jpeg",
  },
  {
    className: "gatto",
    rawCount: 50,
    image: gattoPreview,
    fileName: "1.jpeg",
  },
  {
    className: "mucca",
    rawCount: 40,
    image: muccaPreview,
    fileName: "OIP---lAIbDlHKmejDpqrXq6vAAAAA.jpeg",
  },
  {
    className: "pecora",
    rawCount: 30,
    image: pecoraPreview,
    fileName: "OIP--5EOVD9HIiHEqNd8PZjFogHaII.jpeg",
  },
  {
    className: "ragno",
    rawCount: 25,
    image: ragnoPreview,
    fileName: "OIP--1GKxNzkhVbR_eyVRCdp9QHaE6.jpeg",
  },
  {
    className: "scoiattolo",
    rawCount: 20,
    image: scoiattoloPreview,
    fileName: "OIP--0Yr2a_yg2hs5QgCoHAOnAHaLJ.jpeg",
  },
];

export const falPreviewAssets: FalPreviewAsset[] = previewInputs.map((asset) => {
  const generatedCount = Math.max(0, majorityClassCap - asset.rawCount);

  return {
    id: `fal-${asset.className}`,
    className: asset.className,
    provider: "fal.ai",
    source: "synthetic",
    badge: generatedCount > 0 ? "✨ Fal AI" : "At Cap",
    image: asset.image,
    sourcePath: asset.fileName
      ? `data/animals/fal-ai-generated/${asset.className}/${asset.fileName}`
      : undefined,
    prompt: `Photorealistic ${asset.className} class recovery images for bounded Fal AI balancing; total class count must not exceed 100.`,
    rawCount: asset.rawCount,
    generatedCount,
    majorityClassCap,
  };
});

export const falPreviewTotalGenerated = falPreviewAssets.reduce(
  (total, asset) => total + asset.generatedCount,
  0,
);

export function FalPreviewGallery({ visibleCount }: { visibleCount: number }) {
  const isVisible = visibleCount > 0;
  const visibleAssets = isVisible ? falPreviewAssets : [];

  return (
    <article className={styles.root} aria-label="Fal AI generated image previews">
      <header className={styles.header}>
        <div>
          <span className={styles.kicker}>Fal AI outputs</span>
          <h3>Cached generated recovery images</h3>
        </div>
        <span className={styles.countBadge}>
          {isVisible ? `${falPreviewTotalGenerated} generated` : "0 generated"}
        </span>
      </header>

      <p className={styles.copy}>
        Simulated ZIP ingest reads the unzipped `data/` directory. Cached `fal.ai`
        outputs stay outside `raw-img/` and top up every Animals-10 class to
        exactly 100 images across raw plus generated assets.
      </p>

      <dl className={styles.metaGrid}>
        <div>
          <dt>Raw Input</dt>
          <dd>data/animals/raw-img</dd>
        </div>
        <div>
          <dt>Generated</dt>
          <dd>{isVisible ? falPreviewTotalGenerated : 0}</dd>
        </div>
        <div>
          <dt>Cap</dt>
          <dd>100 per animal</dd>
        </div>
      </dl>

      {visibleAssets.length ? (
        <div className={styles.grid}>
          {visibleAssets.map((asset) => (
            <figure className={styles.card} key={asset.id} data-empty={!asset.image}>
              <span className={styles.imageWrap}>
                {asset.image ? (
                  <Image
                    src={asset.image}
                    alt={`${asset.className} Fal AI generated recovery preview`}
                    fill
                    sizes="(min-width: 1180px) 170px, 45vw"
                    className={styles.image}
                  />
                ) : (
                  <span className={styles.noImage}>Raw class already at cap</span>
                )}
              </span>
              <figcaption>
                <span>{asset.badge}</span>
                <strong>{asset.className}</strong>
                <small>
                  {asset.rawCount} raw + {asset.generatedCount} generated = {asset.majorityClassCap}
                </small>
              </figcaption>
            </figure>
          ))}
        </div>
      ) : (
        <div className={styles.empty}>
          Drag the simulated ZIP into DataForge, then run analysis to reveal the
          bounded Fal AI recovery image previews.
        </div>
      )}
    </article>
  );
}

export function getFalPreviewAssetManifest() {
  return falPreviewAssets.map(({ image, ...asset }) => ({
    ...asset,
    imageUrl: image?.src,
  }));
}
